### ISSUE TITLE
Map not displayed on iOS

### ISSUE THREAD

**Issue by graux** [apptreesoftware/flutter_google_map_view#122]
Hi, I am going a bit mad trying to solve this issue.
I have a fully functional map in Android, with custom markers, but in iOS it won't show the "map" assets.
Meaning: in iOS it shows my custom markers, but I have no background: no streets, buildings, etc. just a gray background with my markers floating around.
No compilation or runtime errors.
Happening in both emulator and device. Using an unrestricted API for now.

Any ideas? thanks

My pubspec:
```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  crypto: any
  shared_preferences: any
  flutter_svg: any
  font_awesome_flutter: any
  http: ^0.11.3+17
  scoped_model: ^0.3.0
  url_launcher: ^3.0.3
  transparent_image: any
  flutter_launcher_icons: "^0.6.1"
  cupertino_icons: ^0.1.2
  rxdart: ^0.18.1
  map_view: ^0.0.14
  package_info: ^0.3.2
  launch_review: ^1.0.1

dev_dependencies:
  # flutter_test:
    # sdk: flutter
  intl_translation: "^0.17.0"
```
