### ISSUE TITLE
An error occur when i run my flutter app in the console

### ISSUE THREAD

**Issue by toregua** [apptreesoftware/flutter_google_map_view#16]
Hi,
Thank you for your really nice plugin.

I met an error when i lauch my flutter app in the console : 

```
Performing full restart...
I/flutter (28990): Configured channel receiver in flutter ..
E/flutter (28990): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (28990): MissingPluginException(No implementation found for method setApiKey on channel com.apptreesoftware.map_view)
E/flutter (28990): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:153:7)
E/flutter (28990): <asynchronous suspension>
E/flutter (28990): #1      MapView.setApiKey (package:map_view/map_view.dart:47:7)
E/flutter (28990): #2      main (/data/user/0/com.yourcompany.sortiesportmobile/cache/sortiesport_mobileLULDVN/sortiesport_mobile/lib/main.dart:20:11)
E/flutter (28990): #3      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:278)
E/flutter (28990): #4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:164)
Restarted app in 5 948ms.
```

My flutter doctor is : 
```
[√] Flutter (on Microsoft Windows [version 10.0.16299.192], locale fr-FR, channel alpha)
    • Flutter version 0.0.21 at C:\Flutter\flutter
    • Framework revision 2e449f06f0 (9 days ago), 2018-01-29 14:26:51 -0800
    • Engine revision 6921873c71
    • Tools Dart version 2.0.0-dev.16.0
    • Engine Dart version 2.0.0-edge.da1f52592ef73fe3afa485385cb995b9aec0181a

[√] Android toolchain - develop for Android devices (Android SDK 27.0.0)
    • Android SDK at D:\Android\android-sdk
    • Android NDK at D:\Android\android-sdk\ndk-bundle
    • Platform android-27, build-tools 27.0.0
    • ANDROID_HOME = D:\Android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Connected devices
    • ONEPLUS A5000 • 6d010b4a • android-arm • Android 8.0.0 (API 26)

```
Is an error due to the new dart version 2.0.0-dev ?
Thanks

**Comment by toregua** [comment]
I think it may be related to the new dart version 

In order to have flutter packages get working i need to change your environnement requirement with sdk: '>=1.9.0 <=2.0.0-dev.16.0' in the pubspec.yaml but package uri: "^0.11.1" that map_view use seem to be not compatible with the new dart 2.0.0-dev.16.0 because flutter packages get fail because of him

**Comment by Samaritan1011001** [comment]
Can you show your pubspec.yaml ? Also have you tried this in the previous dart version?

**Comment by matthewtsmith** [comment]
@johnpryan Can you look at this. I think we dealt with a similar problem in another plugin.

**Comment by toregua** [comment]
@Samaritan1011001 of course : 

```
name: sortiesport_mobile
description: A new Flutter project.

dependencies:
  collection: 1.14.5
  intl: 0.15.1
  # string_scanner: 1.0.2
  url_launcher: ^2.0.1
  http: ^0.11.3+14
  flutter_webview_plugin: '^0.0.5'
  # flutter_facebook_connect: "^0.0.4"
  # built_value: ^1.0.1
  # built_collection: ^1.0.0
  flutter_google_places_autocomplete: "^0.0.4"
  google_maps_webservice: "^0.0.3"
  side_header_list_view: "^0.0.2"
  cached_network_image: "^0.0.2"
  flutter_markdown: "^0.1.1"
  html_unescape: "^0.1.5"
  share: "0.2.2"
  queries: "^0.0.15"
  # map_view: "^0.0.10"
  location: "^1.1.7"
  image_carousel: "0.2.0"
  image_picker: "^0.2.1"
  flutter_flux: '>=4.0.1'
  flutter_facebook_login: "^1.0.2"

  # Also update dev/benchmarks/complex_layout/pubspec.yaml
  flutter_gallery_assets:
    git:
      url: https://flutter.googlesource.com/gallery-assets
      ref: 0b6cdb29b24ecc60781c2828086d955dacdc0152
 
# dev_dependencies:
  # build_runner: ^0.3.0
  # built_value_generator: ^1.0.1
  # flutter_test:
  #   sdk: flutter
  # flutter_driver:
  #   sdk: flutter






# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - lib/assets/logo.png
    - lib/assets/noavatar.png
    - lib/assets/activiteautourdemoi.jpg
    - lib/assets/parcourirannuaire.jpg
    - lib/assets/sortiesavenir.jpg
    - packages/flutter_gallery_assets/appbar_background.jpg
    - packages/flutter_gallery_assets/appbar/appbar_background_layer0.png
    - packages/flutter_gallery_assets/appbar/appbar_background_layer1.png
    - packages/flutter_gallery_assets/appbar/appbar_background_layer2.png
    - packages/flutter_gallery_assets/appbar/appbar_background_layer3.png
    - packages/flutter_gallery_assets/appbar/appbar_background_layer4.png
    - packages/flutter_gallery_assets/appbar/appbar_background_layer5.png
    - packages/flutter_gallery_assets/pesto/avatar.jpg
    - packages/flutter_gallery_assets/pesto/image10.jpg
    - packages/flutter_gallery_assets/pesto/image11.jpg
    - packages/flutter_gallery_assets/pesto/image12.jpg
    - packages/flutter_gallery_assets/pesto/image13.jpg
    - packages/flutter_gallery_assets/pesto/image1.jpg
    - packages/flutter_gallery_assets/pesto/image2.jpg
    - packages/flutter_gallery_assets/pesto/image3.jpg
    - packages/flutter_gallery_assets/pesto/image4.jpg
    - packages/flutter_gallery_assets/pesto/image5.jpg
    - packages/flutter_gallery_assets/pesto/image6.jpg
    - packages/flutter_gallery_assets/pesto/image7.jpg
    - packages/flutter_gallery_assets/pesto/image8.jpg
    - packages/flutter_gallery_assets/pesto/image9.jpg
    - packages/flutter_gallery_assets/pesto/logo_small.png
    - packages/flutter_gallery_assets/pesto/logo_medium.png
    - packages/flutter_gallery_assets/pesto/fish.png
    - packages/flutter_gallery_assets/pesto/healthy.png
    - packages/flutter_gallery_assets/pesto/main.png
    - packages/flutter_gallery_assets/pesto/meat.png
    - packages/flutter_gallery_assets/pesto/quick.png
    - packages/flutter_gallery_assets/pesto/spicy.png
    - packages/flutter_gallery_assets/pesto/veggie.png
    - packages/flutter_gallery_assets/about_logo.png
    - packages/flutter_gallery_assets/ali_connors.jpg
    - packages/flutter_gallery_assets/drawer_logo.png
    - packages/flutter_gallery_assets/kangaroo_valley_safari.jpg
    - packages/flutter_gallery_assets/top_10_australian_beaches.jpg
    - packages/flutter_gallery_assets/landscape_0.jpg
    - packages/flutter_gallery_assets/landscape_1.jpg
    - packages/flutter_gallery_assets/landscape_2.jpg
    - packages/flutter_gallery_assets/landscape_3.jpg
    - packages/flutter_gallery_assets/landscape_4.jpg
    - packages/flutter_gallery_assets/landscape_5.jpg
    - packages/flutter_gallery_assets/landscape_6.jpg
    - packages/flutter_gallery_assets/landscape_7.jpg
    - packages/flutter_gallery_assets/landscape_8.jpg
    - packages/flutter_gallery_assets/landscape_9.jpg
    - packages/flutter_gallery_assets/landscape_10.jpg
    - packages/flutter_gallery_assets/landscape_11.jpg
    - packages/flutter_gallery_assets/shrine/products/backpack.png
    - packages/flutter_gallery_assets/shrine/products/beachball.png
    - packages/flutter_gallery_assets/shrine/products/binoculars.png
    - packages/flutter_gallery_assets/shrine/products/brush.png
    - packages/flutter_gallery_assets/shrine/products/chair.png
    - packages/flutter_gallery_assets/shrine/products/chucks.png
    - packages/flutter_gallery_assets/shrine/products/clock.png
    - packages/flutter_gallery_assets/shrine/products/fish_bowl.png
    - packages/flutter_gallery_assets/shrine/products/flippers.png
    - packages/flutter_gallery_assets/shrine/products/green-shoes.png
    - packages/flutter_gallery_assets/shrine/products/heels.png
    - packages/flutter_gallery_assets/shrine/products/helmet.png
    - packages/flutter_gallery_assets/shrine/products/lawn_chair.png
    - packages/flutter_gallery_assets/shrine/products/lipstick.png
    - packages/flutter_gallery_assets/shrine/products/popsicle.png
    - packages/flutter_gallery_assets/shrine/products/radio.png
    - packages/flutter_gallery_assets/shrine/products/sunnies.png
    - packages/flutter_gallery_assets/shrine/products/surfboard.png
    - packages/flutter_gallery_assets/shrine/products/teapot.png
    - packages/flutter_gallery_assets/shrine/vendors/16c477b.jpg
    - packages/flutter_gallery_assets/shrine/vendors/ali-connors.png
    - packages/flutter_gallery_assets/shrine/vendors/peter-carlsson.png
    - packages/flutter_gallery_assets/shrine/vendors/sandra-adams.jpg
    - packages/flutter_gallery_assets/shrine/vendors/zach.jpg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages

```

and if i uncomment # map_view: "^0.0.10" error arrives when i use "flutter packages get".

Before i run "flutter upgrade" everything was ok with previous dart version
