### ISSUE TITLE
Errors Adding Dependency

### ISSUE THREAD

**Issue by jpgilchrist** [apptreesoftware/flutter_google_map_view#22]
My apologies if this is not on you, but I tried adding the dependency for map_view and it's erring out when I attempt to install the packages. 

```
Package uri has no versions that match >=0.11.1 <0.12.0 derived from:
- map_view 0.0.10 depends on version ^0.11.1
pub get failed (1)
```
```yaml
dependencies:
  flutter:
    sdk: flutter
  fluro: ^1.2.1
  http: ^0.11.3
  scoped_model: ^0.2.0
  timeago: ^1.2.1
  map_view: 0.0.10
```

**Comment by kelvinharron** [comment]
I've got the same problem. I followed the instructions [from here](https://pub.dartlang.org/packages/map_view#-installing-tab-) with and without ''. 

```
Running "flutter packages get" in opendata...
Package uri has no versions that match >=0.11.1 <0.12.0 derived from:
- map_view 0.0.10 depends on version ^0.11.1
pub get failed (1)
Process finished with exit code 1
```

This is a brand new project in IntelliJ with the following dependencies:

```
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  map_view: ^0.0.10
```

I guess a solution would be to clone this repo and import the file that way. Would be nice to resolve this as it will frustrate newcomers.
