### ISSUE TITLE
flutter packages get failed  

### ISSUE THREAD

**Issue by initiuminc1** [apptreesoftware/flutter_google_map_view#31]
```
Running "flutter packages get" in flutter-playbooks...
Package dart_style has no versions that match >=1.0.0 <2.0.0 derived from:
- build_runner 0.7.6 depends on version ^1.0.0
pub get failed (1)
Process finished with exit code 1
```

Dependencies 
```
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #https://github.com/Solido/awesome-flutter
  json_annotation: ^0.2.2
  cupertino_icons: ^0.1.0
  english_words: ^3.1.0
  fluro: ^1.3.1 #https://github.com/goposse/fluro
  map_view: ^0.0.10
```
